name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B package --file pom.xml
      - name: Compress generated file
        id: compress_generated_files
        run: zip -r Spawners target/
      - name: Discord notification (O)
        if: github.ref == 'refs/heads/master'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_O }}
        with:
          args: ':new: Spawners が更新されました: https://github.com/SiroPlugins/Spawners'
      - name: Send generated files to Discord (O)
        uses: sinshutu/upload-to-discord@master
        if: github.ref == 'refs/heads/master'
        env:
          DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_O }}
        with:
          args: Spawners.zip